<a href="https://colab.research.google.com/github/kimyujin0/Tensorflow/blob/main/Tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
# tensorflow의 가장 기초적인 자료형
tensor = tf.constant(3)
print(tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
tensor = tf.constant( [3,4,5])
tensor2 = tf.constant([ 6,7,8])
print(tensor+tensor2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [6]:
 # 행렬의 상하배치
 tensor3 = tf.constant([[1,2],
                        [3,4]])

In [7]:
# 행렬간의 덧셈
print(tf.add(tensor, tensor2))

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [10]:
tensor4= tf.zeros([2,2,3])
print(tensor4)
# 뒤에서부터 해석, 3개의 0이 들어있는 행 2개를 생성하고 그것들을 2개 생성

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [11]:
print(tensor.shape)
# 자료가 3개 들어있다.
# shape 해석이 중요 몇 차원의 데이터인지 알아야 분석이 쉬움

(3,)


In [12]:
print(tensor3.shape)
# 2개의 데이터가 2개 있다

(2, 2)


In [ ]:
tf.cast()
# 데이터 타입을 바꾸는 함수

In [13]:
# weight 만들기
w = tf.Variable(1.0)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [14]:
# 할당량 변경
w.assign(2)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
