<a href="https://colab.research.google.com/github/kimyujin0/Tensorflow/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
t1 = tf.constant([1,2,3])
t2 = tf.constant([10,20,30])

In [4]:
print(t1+t2)
print(t1-t2)
print(t1*t2)
print(t1/t2)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)


In [7]:
t3 = tf.random.normal(shape=(3,4), stddev=5, mean=0)
t4 = tf.random.normal(shape=(3,4), stddev=5, mean=0)

In [9]:
print(t3.numpy(),'\n')
print(t4.numpy(),'\n')

[[-3.8009465  -0.10121017 -1.318499    6.856401  ]
 [ 3.9273157   2.505038   -6.9442997   4.787032  ]
 [ 4.4839697  -0.7826138   3.0637197  -9.808319  ]] 

[[-2.2965548   6.8105946  -4.439709   -2.109042  ]
 [-4.8954287   9.0479145   5.9249773  -5.3478975 ]
 [-2.003117   -0.49166086 -3.0944834  -3.8483267 ]] 



In [10]:
t4 = tf.cast(t4, dtype=tf.int16)
t5 = tf.reduce_sum(t4)
print(t5.numpy())

-5


In [12]:
t6 = tf.reduce_sum(t4,axis=0)
print(t6.numpy())

[ -8  15  -2 -10]


In [13]:
t7 = tf.random.normal(shape=(128,128,3),mean=0,stddev=5)
t7 = tf.cast(t7, dtype=tf.int16)
t8 = tf.reduce_sum(t7, axis=2)
print(t7.shape,'\n')
print(t8.shape)

(128, 128, 3) 

(128, 128)


In [14]:
t9 = tf.random.normal(shape=(128,128,3),mean=0,stddev=5)
t9 = tf.cast(t9, dtype=tf.int16)
t10 = tf.reduce_max(t9, axis=2)
print(t9.shape,'\n')
print(t10.shape) 

(128, 128, 3) 

(128, 128)
