<a href="https://colab.research.google.com/github/kimyujin0/Tensorflow/blob/main/Variable%EA%B3%BC_constant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
import numpy as np

In [3]:
t1 = tf.Variable([1,2,3])
t2 = tf.constant([1,2,3])

In [4]:
print(t1)
print(t2)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
print(type(t1)) # dataset 안 모델 안에서 학습되는 것
print(type(t2)) # 변할수가 없는 것(dataset같은)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
test_list = [1,2,3]
test_np = np.array([1,2,3])

In [9]:
t1 = tf.constant(t1)
t2 = tf.constant(test_np)

In [10]:
print(t1)
print(t2)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [11]:
test_list = [1,2,3]
test_np = np.array([1,2,3])

In [12]:
t1 = tf.Variable(t1)
t2 = tf.Variable(test_np)

In [13]:
print(t1)
print(t2)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([1, 2, 3])>


In [15]:
t1 = tf.constant(test_list)
t2 = tf.Variable(test_list)
t3 = tf.Variable(t1)
# constant tensor는 Variable로 변환 가능
# Variable tensor는 constant로 변환 불가

In [16]:
# Variable tensor -> constant tensor
t4 = tf.convert_to_tensor(test_list)
t5 = tf.convert_to_tensor(test_np)
print(type(t4))
print(type(t5))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [17]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

In [21]:
t1 = tf.constant(test_list1)
t2 = tf.constant(test_list2)
t3 = t1+t2
print(type(t3))
# constant와 constant, Variable과 Variable 사칙연산 가능

<class 'tensorflow.python.framework.ops.EagerTensor'>
